version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    env_file: .env
    restart: always
  wordpress:
    container_name: ${APP_ID}
    expose:
      - "80"

    depends_on:
      - db
    build: .
    volumes:
      - wordpress-data:/var/www/html
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      VIRTUAL_HOST: ${HOSTNAME}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${HOSTNAME}
      LETSENCRYPT_EMAIL: ${EMAIL}
    networks:
      - proxy
    restart: unless-stopped

volumes:
  db-data:
    external:
      name: "${APP_ID}-db-data"
  wordpress-data:
    external:
      name: "${APP_ID}-wordpress-data"

networks:
  proxy:
    external:
      name: nginx-proxy